###
POST http://localhost:8081/api/v1/shelters
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="dto"
Content-Type: application/json

{
  "name": "КотоПес",
  "address": "г. Астана, ул. Тихая 11, стр. 1",
  "phoneNumber": "77776665544",
  "timeTable": "Пн-Пт 9:00-18:00"
}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="266-16.jpg"
Content-Type: image/jpeg

< 266-16.jpg
--WebAppBoundary--